ROSTER_FILE = "ALL_ROSTERS.json"
PLAYER_OBJECTS_FILE = "ALL_PLAYER_OBJECTS.json"
RAW_SCHEDULE_FILE = "MASTER_SCHEDULE_RAW.json"
SCHEDULE_FILE = "MASTER_SCHEDULE.json"
PREDICTION_FILE = "PREDICTION.csv"

MONEYPUCK_MASTER_STATS = "MP_ALL_YEARS.json"

YAHOO_RAW = "YAHOO_RAW.json"
MY_TEAM_FILE = "myTeam.json"
GAME_WEEKS_FILE = "ALL_GAMEWEEKS.json"

YAHOO_TEAM_NAME = "Crayton Kerrer"
REG_SZN_WEEKS = 20
PLAYOFF_WEEKS = 3

CURRENT_SEASON = 20242025

TEAM_CODES = [
"ANA",
"BOS",
"BUF",
"CAR",
"CBJ",
"CGY",
"CHI",
"COL",
"DAL",
"DET",
"EDM",
"FLA",
"LAK",
"MIN",
"MTL",
"NJD",
"NSH",
"NYI",
"NYR",
"OTT",
"PHI",
"PIT",
"SEA",
"SJS",
"STL",
"TBL",
"TOR",
"UTA",
"VAN",
"VGK",
"WPG",
"WSH"
]